/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brainbox;

import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author User
 */
public class BrainMaster extends javax.swing.JFrame {

     private String username; // Store the username
    private int quizDuration; // Store quiz timer duration in minutes
    private String selectedDifficulty; // Difficulty for the quiz
    private String selectedCategory; // Category for the quiz

    public BrainMaster(String username) {
        this.username = username;
        initComponents();
        welcomeUser();
    }

    private void welcomeUser() {
        wel.setText("Welcome, " + username + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        toCreate = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        access = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        toBoard = new javax.swing.JLabel();
        main = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        option = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        wel = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        options.setkEndColor(new java.awt.Color(206, 92, 165));
        options.setkStartColor(new java.awt.Color(29, 0, 71));
        options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toCreate.setText("Create Quiz");
        toCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toCreateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        options.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 40));

        access.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        access.setText("Account Access");
        access.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accessMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(access, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(access, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        options.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 40));

        toBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toBoard.setText("Leaderboards");
        toBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toBoardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        options.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 40));

        getContentPane().add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        main.setkEndColor(new java.awt.Color(206, 92, 165));
        main.setkStartColor(new java.awt.Color(240, 122, 46));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 122, 46));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        option.setText("Options");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(option)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(option)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel5.setText("Profile Area");
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 50));

        jLabel6.setText("Username ");
        main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        wel.setText("Home");
        main.add(wel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel8.setText("Points gained");
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("About us");
        main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 330, 150));

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 690, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toCreateMouseClicked
          ChooseDifficulty difficultySelector = new ChooseDifficulty();
        difficultySelector.setVisible(true);

        difficultySelector.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                selectedDifficulty = difficultySelector.getSelectedDifficulty();

                if (selectedDifficulty == null) {
                    JOptionPane.showMessageDialog(null, "Quiz setup was not completed!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String durationInput = JOptionPane.showInputDialog("Set quiz duration in minutes:");
                try {
                    quizDuration = Integer.parseInt(durationInput);
                    if (quizDuration <= 0) {
                        throw new NumberFormatException();
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Invalid duration! Please enter a positive integer.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Assuming createQuiz has a constructor that accepts only difficulty and duration
                createQuiz quizCreator = new createQuiz(selectedDifficulty, quizDuration);
                quizCreator.setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_toCreateMouseClicked

    private void toBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toBoardMouseClicked
        LeaderBoards li = new LeaderBoards();
        li.pack();
        li.setVisible(true);
        li.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_toBoardMouseClicked

    private void accessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessMouseClicked
        AccountAccess ac = new AccountAccess();
        ac.pack();
        ac.setVisible(true);
        ac.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_accessMouseClicked

   

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new BrainMaster("defaultUser").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel access;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private keeptoo.KGradientPanel main;
    private javax.swing.JLabel option;
    private keeptoo.KGradientPanel options;
    private javax.swing.JLabel toBoard;
    private javax.swing.JLabel toCreate;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
