/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brainbox;

/**
 *
 * @author User
 */
public class Braineer extends javax.swing.JFrame {

    private String username;

    public Braineer(String username) {
        this.username = username; // Store the username
        initComponents();
        welcomeUser();
    }

    private Braineer() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void welcomeUser() {
        // Display a welcome message with the username
        jLabel7.setText("Welcome, " + username + "!");
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        toQuiz = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        boards = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Review = new javax.swing.JLabel();
        main = new keeptoo.KGradientPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        options.setkEndColor(new java.awt.Color(206, 92, 165));
        options.setkStartColor(new java.awt.Color(29, 0, 71));
        options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toQuiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toQuiz.setText("Take Quiz");
        toQuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toQuizMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toQuiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toQuiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        options.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 40));

        boards.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boards.setText("Leaderboards");
        boards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boards, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boards, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        options.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 40));

        Review.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Review.setText("Review Quiz");
        Review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReviewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Review, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Review, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        options.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 40));

        getContentPane().add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        main.setkEndColor(new java.awt.Color(206, 92, 165));
        main.setkStartColor(new java.awt.Color(240, 122, 46));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 122, 46));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Options");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel5.setText("Profile Area");
        main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 50));

        jLabel6.setText("Username ");
        main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel7.setText("Home");
        main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel8.setText("Points gained");
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("About us");
        main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 330, 150));

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 690, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toQuizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toQuizMouseClicked
        ChooseDifficulty ti = new ChooseDifficulty();
        ti.pack();
        ti.setVisible(true);
        ti.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_toQuizMouseClicked

    private void ReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReviewMouseClicked
        ReviewQuiz ri = new ReviewQuiz();
        ri.pack();
        ri.setVisible(true);
        ri.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ReviewMouseClicked

    private void boardsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardsMouseClicked
        LeaderBoards li = new LeaderBoards();
        li.pack();
        li.setVisible(true);
        li.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_boardsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Braineer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Review;
    private javax.swing.JLabel boards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private keeptoo.KGradientPanel main;
    private keeptoo.KGradientPanel options;
    private javax.swing.JLabel toQuiz;
    // End of variables declaration//GEN-END:variables
}
