/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brainbox;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ChooseDifficulty extends javax.swing.JFrame {

     private String selectedDifficulty;

    public ChooseDifficulty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseCategory = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        easy = new javax.swing.JButton();
        mix = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooseCategory.setkEndColor(new java.awt.Color(206, 92, 165));
        chooseCategory.setkStartColor(new java.awt.Color(240, 122, 46));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose Dfficulty");

        jButton1.setText("Medium");
        jButton1.setMaximumSize(new java.awt.Dimension(76, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(76, 22));
        jButton1.setPreferredSize(new java.awt.Dimension(76, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hard");
        jButton2.setMaximumSize(new java.awt.Dimension(76, 22));
        jButton2.setMinimumSize(new java.awt.Dimension(76, 22));
        jButton2.setPreferredSize(new java.awt.Dimension(76, 22));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        easy.setText("Easy");
        easy.setMaximumSize(new java.awt.Dimension(76, 22));
        easy.setMinimumSize(new java.awt.Dimension(76, 22));
        easy.setPreferredSize(new java.awt.Dimension(76, 22));
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });

        mix.setText("Shuffle");
        mix.setMaximumSize(new java.awt.Dimension(76, 22));
        mix.setMinimumSize(new java.awt.Dimension(76, 22));
        mix.setPreferredSize(new java.awt.Dimension(76, 22));
        mix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseCategoryLayout = new javax.swing.GroupLayout(chooseCategory);
        chooseCategory.setLayout(chooseCategoryLayout);
        chooseCategoryLayout.setHorizontalGroup(
            chooseCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseCategoryLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(chooseCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(chooseCategoryLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(chooseCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(easy, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mix, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(324, 324, 324))
        );
        chooseCategoryLayout.setVerticalGroup(
            chooseCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseCategoryLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(easy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mix, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chooseCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chooseCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyActionPerformed

    private void mixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mixActionPerformed
     private void setDifficulty(String difficulty) {
        selectedDifficulty = difficulty;
        JOptionPane.showMessageDialog(this, "Difficulty set to: " + difficulty, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    private void proceedToQuiz() {
        if (selectedDifficulty == null) {
            JOptionPane.showMessageDialog(this, "Please select a difficulty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Difficulty: " + selectedDifficulty, "Selections", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }

    public String getSelectedDifficulty() {
        return selectedDifficulty;
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new ChooseDifficulty().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel chooseCategory;
    private javax.swing.JButton easy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mix;
    // End of variables declaration//GEN-END:variables
}
