/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brainbox;

/**
 *
 * @author User
 */
public class Mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu
     */
    public Mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        brainmaster = new javax.swing.JButton();
        braineer = new javax.swing.JButton();
        guest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(880, 562));

        kGradientPanel1.setkEndColor(new java.awt.Color(144, 65, 112));
        kGradientPanel1.setkStartColor(new java.awt.Color(162, 81, 48));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brainbox/storage/loadingShy.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -40, 500, 400));

        brainmaster.setBackground(new java.awt.Color(204, 102, 0));
        brainmaster.setForeground(new java.awt.Color(255, 255, 255));
        brainmaster.setText("Brain Master");
        brainmaster.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        brainmaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brainmasterActionPerformed(evt);
            }
        });
        kGradientPanel1.add(brainmaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 110, 30));

        braineer.setBackground(new java.awt.Color(204, 102, 0));
        braineer.setForeground(new java.awt.Color(255, 255, 255));
        braineer.setText("Braineer");
        braineer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        braineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                braineerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(braineer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 110, 30));

        guest.setBackground(new java.awt.Color(204, 102, 0));
        guest.setForeground(new java.awt.Color(255, 255, 255));
        guest.setText("Guest");
        guest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestActionPerformed(evt);
            }
        });
        kGradientPanel1.add(guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brainmasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brainmasterActionPerformed
        Login lo = new Login();
        lo.pack();
        lo.setLocationRelativeTo(null);
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_brainmasterActionPerformed

    private void braineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_braineerActionPerformed
        Login lo = new Login();
        lo.pack();
        lo.setLocationRelativeTo(null);
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_braineerActionPerformed

    private void guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestActionPerformed
        GuestQuiz g = new GuestQuiz();
        g.pack();
        g.setVisible(true);
        g.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_guestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton braineer;
    private javax.swing.JButton brainmaster;
    private javax.swing.JButton guest;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
