/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brainbox;

//importing packages/statements....
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class SignUp extends javax.swing.JFrame {

    private String uname, password, confirm, selectedRole;
    private static final String FILEPATH = "C:\\Users\\User\\Documents\\NetBeansProjects\\brainBox\\src\\brainbox\\DataBase\\Bash.json";
    private final JSONParser opener = new JSONParser();
    private JSONArray teacherList = new JSONArray();
    private JSONArray studentList = new JSONArray();
    private JSONObject record = new JSONObject();

    public SignUp() {
        initComponents();
        loadUserData();
    }

    private void loadUserData() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        keeptoo.KGradientPanel kGradientPanel1 = new keeptoo.KGradientPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        textCre = new javax.swing.JLabel();
        keeptoo.KGradientPanel kGradientPanel2 = new keeptoo.KGradientPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        sign = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        log1 = new javax.swing.JButton();
        role = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        jpas = new javax.swing.JTextField();
        conpas = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(935, 545));

        kGradientPanel1.setBackground(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkEndColor(new java.awt.Color(206, 92, 165));
        kGradientPanel1.setkStartColor(new java.awt.Color(240, 122, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizapplication/output-onlinegiftools (1).gif"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brainbox/storage/output-onlinegiftools (1).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(97, 97, 97)
                .addComponent(jLabel8))
        );

        textCre.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textCre.setForeground(new java.awt.Color(247, 247, 247));
        textCre.setText("Create an Account");

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(247, 247, 247))); // NOI18N
        kGradientPanel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        kGradientPanel2.setkEndColor(new java.awt.Color(206, 92, 165));
        kGradientPanel2.setkGradientFocus(430);
        kGradientPanel2.setkStartColor(new java.awt.Color(221, 106, 109));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 247, 247));
        jLabel2.setText("User Name:");

        jname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jname.setForeground(new java.awt.Color(0, 51, 51));
        jname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnameMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jnameMouseReleased(evt);
            }
        });
        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 247, 247));
        jLabel3.setText("Already have an account?");

        sign.setBackground(new java.awt.Color(211, 96, 146));
        sign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sign.setForeground(new java.awt.Color(0, 51, 204));
        sign.setText("Sign In");
        sign.setBorder(null);
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 247, 247));
        jLabel5.setText("Password:");

        log1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        log1.setForeground(new java.awt.Color(0, 51, 51));
        log1.setText("Create Account");
        log1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log1ActionPerformed(evt);
            }
        });

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher", "Student" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 247, 247));
        jLabel6.setText("Confirm Password:");

        jpas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpas.setForeground(new java.awt.Color(0, 51, 51));
        jpas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpasMouseReleased(evt);
            }
        });
        jpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasActionPerformed(evt);
            }
        });

        conpas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        conpas.setForeground(new java.awt.Color(0, 51, 51));
        conpas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conpasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                conpasMouseReleased(evt);
            }
        });
        conpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sign)
                .addGap(118, 118, 118))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jname)
                    .addComponent(role, 0, 175, Short.MAX_VALUE)
                    .addComponent(conpas)
                    .addComponent(jpas))
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(log1)
                .addGap(127, 127, 127))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(log1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(textCre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textCre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    private void log1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log1ActionPerformed
        uname = jname.getText().trim();
        password = jpas.getText().trim();
        confirm = conpas.getText().trim();
        selectedRole = role.getSelectedItem().toString().toLowerCase();

        // Validate fields
        if (uname.isEmpty() || password.isEmpty() || confirm.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!password.equals(confirm)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            filecheck();

            // Check for duplicate username
            if (isUsernameTaken(uname)) {
                JOptionPane.showMessageDialog(this, "Username already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Add new user
            JSONObject newUser = new JSONObject();
            newUser.put("username", uname);
            newUser.put("password", password);
            newUser.put("role", selectedRole);

            if ("teacher".equals(selectedRole)) {
                teacherList.add(newUser);
            } else {
                studentList.add(newUser);
            }

            record.put("teacher", teacherList);
            record.put("student", studentList);

            save();

            // Show non-blocking success message and redirect to login
        
            JDialog dialog = new JDialog(this, "Success", true);
            JLabel messageLabel = new JLabel("Successfully Registered!", JLabel.CENTER);
            messageLabel.setFont(new Font("Arial", Font.PLAIN, 14));
            dialog.add(messageLabel);
            dialog.setSize(300, 150);
            dialog.setLocationRelativeTo(this);

            // Set a timer to automatically close the dialog and redirect
            Timer timer = new Timer(1000, e -> {
                dialog.dispose(); // Close the message dialog after 1 second
                Login lo = new Login(); // Redirect to login class
                lo.setVisible(true);
                lo.setLocationRelativeTo(null);
                this.dispose(); // Close the signup form
            });
            timer.setRepeats(false); // Ensure the timer only runs once
            timer.start();

            dialog.setVisible(true); // Display the dialog

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error saving user data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean isUsernameTaken(String username) {
        for (Object obj : teacherList) {
            JSONObject user = (JSONObject) obj;
            if (user.get("username").toString().equalsIgnoreCase(username)) {
                return true;
            }
        }
        for (Object obj : studentList) {
            JSONObject user = (JSONObject) obj;
            if (user.get("username").toString().equalsIgnoreCase(username)) {
                return true;
            }
        }
        return false;


    }//GEN-LAST:event_log1ActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void jnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnameMouseClicked
        jname.setText("");
    }//GEN-LAST:event_jnameMouseClicked

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed
        Login lo = new Login();
        lo.pack();
        lo.setVisible(true);
        lo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_signActionPerformed

    private void jpasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasMouseClicked
        jpas.setText("");
    }//GEN-LAST:event_jpasMouseClicked

    private void jpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasActionPerformed

    private void conpasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conpasMouseClicked
        conpas.setText("");
    }//GEN-LAST:event_conpasMouseClicked

    private void conpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpasActionPerformed

    private void conpasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conpasMouseReleased
        conpas.setText("");
    }//GEN-LAST:event_conpasMouseReleased

    private void jpasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasMouseReleased
        jpas.setText("");
    }//GEN-LAST:event_jpasMouseReleased

    private void jnameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnameMouseReleased
        jname.setText("");
    }//GEN-LAST:event_jnameMouseReleased
    public void filecheck() throws FileNotFoundException, IOException, ParseException {
        try (FileReader reader = new FileReader(FILEPATH)) {
            if (reader.ready()) {
                record = (JSONObject) opener.parse(reader);
                teacherList = (JSONArray) record.getOrDefault("teacher", new JSONArray());
                studentList = (JSONArray) record.getOrDefault("student", new JSONArray());
            }
        }
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            SignUp log1 = new SignUp();
            log1.setVisible(true);
            log1.pack();
            log1.setLocationRelativeTo(null);

        });
    }

    public void save() throws IOException {
        try (FileWriter file = new FileWriter(FILEPATH)) {
            file.write(record.toJSONString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conpas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jpas;
    private javax.swing.JButton log1;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton sign;
    private javax.swing.JLabel textCre;
    // End of variables declaration//GEN-END:variables
}
