/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brainbox;

import java.awt.Font;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

public class SplashScreen extends javax.swing.JFrame {

   
    public SplashScreen() {
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keeptoo.KGradientPanel kGradientPanel1 = new keeptoo.KGradientPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        loadinglabel = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();
        loadingVal = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkEndColor(new java.awt.Color(206, 92, 165));
        kGradientPanel1.setkStartColor(new java.awt.Color(240, 122, 46));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 423, -1, -1));

        loadinglabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        loadinglabel.setForeground(new java.awt.Color(255, 255, 255));
        loadinglabel.setText("Loading...");
        kGradientPanel1.add(loadinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        progressbar.setBackground(new java.awt.Color(255, 255, 255));
        progressbar.setForeground(new java.awt.Color(204, 0, 153));
        kGradientPanel1.add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 542, 27));

        loadingVal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        loadingVal.setForeground(new java.awt.Color(255, 255, 255));
        loadingVal.setText("0%");
        kGradientPanel1.add(loadingVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, -1, -1));

        name.setFont(new java.awt.Font("Verdana", 1, 44)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("BrainBox");
        kGradientPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 400, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brainbox/loading_1.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
            

      public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            SplashScreen splash = new SplashScreen();
            splash.pack();
            splash.setLocationRelativeTo(null);
            splash.setVisible(true);

            new SwingWorker<Void, Integer>() {
                @Override
                protected Void doInBackground() throws Exception {
                    try {
                        for (int i = 0; i <= 100; i++) {
                            Thread.sleep(100);
                            publish(i);

                            if (i == 10) {
                                splash.loadinglabel.setText("Turning Modules...");
                            }
                            if (i == 20) {
                                splash.loadinglabel.setText("Loading Modules...");
                            }
                            if (i == 50) {
                                splash.loadinglabel.setText("Connecting to Database...");
                            }
                            if (i == 70) {
                                splash.loadinglabel.setText("Connection Successfully...");
                            }
                            if (i == 80) {
                                splash.loadinglabel.setText("Launching Application...");
                            }
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    return null;
                }

                @Override
                protected void process(java.util.List<Integer> chunks) {
                    int value = chunks.get(chunks.size() - 1);
                    splash.loadingVal.setText(value + "%");
                    splash.progressbar.setValue(value);
                }

                @Override
                protected void done() {
                    splash.dispose(); // Close the splash screen
                    Mainmenu mainMenu = new Mainmenu(); // Show the main menu
                    mainMenu.pack();
                    mainMenu.setLocationRelativeTo(null); // Center the main menu
                    mainMenu.setVisible(true);
                }
            }.execute();
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loadingVal;
    private javax.swing.JLabel loadinglabel;
    private javax.swing.JLabel name;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables
}
